### PR TITLE
Implement except for walk case

### PR DESCRIPTION
**Pull request by TheSgrash**

### CODE REVIEW

**Review by herrjulz — COMMENTED** [review]
Hey @TheSgrash, the changes look good to me.
May I ask you to update the tests too?

**Comment by TheSgrash** [comment]
@herrjulz as far as I see this case is already covered by [the test starting at line 379](https://github.com/herrjulz/aviator/blob/13c33b06014a7e512b140b37da2d6cd9b17ac54e/processor/processor_test.go#L379)

**Comment by herrjulz** [comment]
@TheSgrash Not really. The test you referenced covers ForEach. Walk tests are [here]( https://github.com/herrjulz/aviator/blob/13c33b06014a7e512b140b37da2d6cd9b17ac54e/processor/processor_test.go#L450). So the Walk tests require an extra test to be tested in combination with "except". Does that help?

**Comment by TheSgrash** [comment]
@herrjulz pls review it now

**Pull request merged**
